[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = 'chip-soil-moisture-sensor'
binary = 'dist/chip-soil-moisture-sensor.wasm'
